### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by ale123715** [Techblogogy/magic-mirror-base#31]
Good Night!
Hi, I'm Brazilian and I really enjoyed your project.
I'm getting the following error while executing "mirror":

Traceback (most recent call last):
  File "/usr/local/bin/mirror", line 2, in <module>
    from server_public import create_server
  File "/home/pi/magic-mirror-base/server/server_public.py", line 14, in <module>
    from server import PServer
  File "/home/pi/magic-mirror-base/server/server.py", line 12, in <module>
    SLEEP_TIME = cfg.getint("GLOBALS", "sleep_time")
  File "/usr/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'GLOBALS'

I'm a beginner, I need help = D. How do I configure the config file?

**Comment by ghost** [comment]
Did you ever get this fixed?

**Comment by ale123715** [comment]
No

Em Dom, 9 de dez de 2018 19:40, thuggathugga <notifications@github.com>
escreveu:

**Comment by safaaelbrans** [comment]
can you help me please i need the source code The Smart Mirror lets me book an Uber, check emails, Facebook & Twitter
